// @flow

export const SET_CUSTOMER_REQUEST = 'CUSTOMER/SET_CUSTOMER_REQUEST';
export const SET_CUSTOMER_SUCESS = 'CUSTOMER/SET_CUSTOMER_SUCESS';
export const SET_ERROR_MESSAGE = 'User/SET_ERROR_MESSAGE';
export const CUSTOMER_INFO_REQUEST = 'CUSTOMER/CUSTOMER_INFO_REQUEST';
export const CUSTOMER_INFO_SUCCESS = 'CUSTOMER/CUSTOMER_INFO_SUCCESS';
export const UPLOAD_REQUEST = 'ADD/UPLOAD_REQUEST';