// @flow

export const MINI_SIDENAV = 'THEME/MINI_SIDENAV';
export const TRANSPARENT_SIDENAV = 'THEME/TRANSPARENT_SIDENAV';
export const SIDENAV_COLOR = 'THEME/SIDENAV_COLOR';
export const TRANSPARENT_NAVBAR = 'THEME/TRANSPARENT_NAVBAR';
export const FIXED_NAVBAR = 'THEME/FIXED_NAVBAR';
export const OPEN_CONFIGURATOR = 'THEME/OPEN_CONFIGURATOR';
export const DIRECTION = 'THEME/DIRECTION';
export const LAYOUT = 'THEME/LAYOUT';
