// flow-typed signature: 8f3e967c4d033353029f98e4d7825efd
// flow-typed version: <<STUB>>/@mysticatea/eslint-plugin_v^13.0.0/flow_v0.152.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mysticatea/eslint-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mysticatea/eslint-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mysticatea/eslint-plugin/lib/configs' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_base' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_browser-globals' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_override-2015' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_override-2016' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_override-2017' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_override-2018' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_override-2019' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_override-2020' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_override-mocha' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_override-special' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_override-ts' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/_override-vue' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/+browser' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/+eslint-plugin' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/+modules' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/+node' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/es2015' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/es2016' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/es2017' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/es2018' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/es2019' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/es2020' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/configs/es5' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/foreign-rules/eslint-comments' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/foreign-rules/eslint-plugin' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/foreign-rules/node' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/foreign-rules/prettier' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/foreign-rules/ts' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/foreign-rules/vue' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/processors' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/processors/vue' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/rules' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/rules/arrow-parens' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/rules/block-scoped-var' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/rules/no-instanceof-array' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/rules/no-instanceof-wrapper' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/rules/no-literal-call' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/rules/no-this-in-static' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/rules/no-use-ignored-vars' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/rules/no-useless-rest-spread' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/rules/prefer-for-of' {
  declare module.exports: any;
}

declare module '@mysticatea/eslint-plugin/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mysticatea/eslint-plugin/index' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin'>;
}
declare module '@mysticatea/eslint-plugin/index.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_base.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_base'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_browser-globals.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_browser-globals'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_override-2015.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_override-2015'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_override-2016.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_override-2016'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_override-2017.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_override-2017'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_override-2018.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_override-2018'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_override-2019.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_override-2019'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_override-2020.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_override-2020'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_override-mocha.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_override-mocha'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_override-special.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_override-special'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_override-ts.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_override-ts'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/_override-vue.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/_override-vue'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/+browser.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/+browser'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/+eslint-plugin.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/+eslint-plugin'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/+modules.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/+modules'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/+node.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/+node'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/es2015.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/es2015'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/es2016.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/es2016'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/es2017.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/es2017'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/es2018.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/es2018'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/es2019.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/es2019'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/es2020.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/es2020'>;
}
declare module '@mysticatea/eslint-plugin/lib/configs/es5.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/configs/es5'>;
}
declare module '@mysticatea/eslint-plugin/lib/foreign-rules/eslint-comments.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/foreign-rules/eslint-comments'>;
}
declare module '@mysticatea/eslint-plugin/lib/foreign-rules/eslint-plugin.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/foreign-rules/eslint-plugin'>;
}
declare module '@mysticatea/eslint-plugin/lib/foreign-rules/node.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/foreign-rules/node'>;
}
declare module '@mysticatea/eslint-plugin/lib/foreign-rules/prettier.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/foreign-rules/prettier'>;
}
declare module '@mysticatea/eslint-plugin/lib/foreign-rules/ts.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/foreign-rules/ts'>;
}
declare module '@mysticatea/eslint-plugin/lib/foreign-rules/vue.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/foreign-rules/vue'>;
}
declare module '@mysticatea/eslint-plugin/lib/processors.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/processors'>;
}
declare module '@mysticatea/eslint-plugin/lib/processors/vue.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/processors/vue'>;
}
declare module '@mysticatea/eslint-plugin/lib/rules.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/rules'>;
}
declare module '@mysticatea/eslint-plugin/lib/rules/arrow-parens.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/rules/arrow-parens'>;
}
declare module '@mysticatea/eslint-plugin/lib/rules/block-scoped-var.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/rules/block-scoped-var'>;
}
declare module '@mysticatea/eslint-plugin/lib/rules/no-instanceof-array.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/rules/no-instanceof-array'>;
}
declare module '@mysticatea/eslint-plugin/lib/rules/no-instanceof-wrapper.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/rules/no-instanceof-wrapper'>;
}
declare module '@mysticatea/eslint-plugin/lib/rules/no-literal-call.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/rules/no-literal-call'>;
}
declare module '@mysticatea/eslint-plugin/lib/rules/no-this-in-static.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/rules/no-this-in-static'>;
}
declare module '@mysticatea/eslint-plugin/lib/rules/no-use-ignored-vars.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/rules/no-use-ignored-vars'>;
}
declare module '@mysticatea/eslint-plugin/lib/rules/no-useless-rest-spread.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/rules/no-useless-rest-spread'>;
}
declare module '@mysticatea/eslint-plugin/lib/rules/prefer-for-of.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/rules/prefer-for-of'>;
}
declare module '@mysticatea/eslint-plugin/lib/utils.js' {
  declare module.exports: $Exports<'@mysticatea/eslint-plugin/lib/utils'>;
}
