// @flow

export const SET_ADDRESS_REQUEST = 'ADDRESS/SET_ADDRESS_REQUEST';
export const SET_ADDRESS_SUCESS = 'ADDRESS/SET_ADDRESS_SUCESS';
export const ADDRESS_INFO_REQUEST = 'ADDRESS/ADDRESS_INFO_REQUEST';
export const ADDRESS_INFO_SUCCESS = 'ADDRESS/ADDRESS_INFO_SUCCESS';
export const UPLOAD_REQUEST = 'ADD/UPLOAD_REQUEST';