// @flow

export const SET_ORDERITEM_REQUEST = 'ORDERITEM/SET_ORDERITEM_REQUEST';
export const SET_ORDERITEM_SUCCESS = 'ORDERITEM/SET_ORDERITEM_SUCCESS';
export const ORDERITEM_INFO_REQUEST = 'ORDERITEM/ORDERITEM_INFO_REQUEST';
export const ORDERITEM_INFO_SUCCESS = 'ORDERITEM/ORDERITEM_INFO_SUCCESS';
