// @flow

export const SET_ERROR_MESSAGE = 'User/SET_ERROR_MESSAGE';
export const INVITE_USER_REQUEST = 'User/INVITE_USER_REQUEST';
export const INVITE_USER_SUCCESS = 'User/INVITE_USER_SUCCESS';
export const FETCH_STORE_OWNER_REQUEST = 'User/FETCH_STORE_OWNER_REQUEST';
export const FETCH_STORE_OWNER_SUCCESS = 'User/FETCH_STORE_OWNER_SUCCESS';
